/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as proofOfReserveSol from "./ProofOfReserve.sol";
export type { proofOfReserveSol };
export type { USDC } from "./USDC";
